name: Pull Request Validation

on:
  pull_request:
    branches: [master]

jobs:
  pull-request-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract version from version.go
        id: get_version
        run: |
          VERSION=$(grep 'const Version =' cmd/upload-ms/version.go | sed 's/[^0-9.]//g')
          if [ -z "$VERSION" ]; then
            echo "Version could not be extracted, exiting..."
            exit 1
          fi
            echo "Extracted version: $VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Check if Docker tag already exists
        run: |
            echo "Checking if tag $VERSION exists..."
            response=$(curl -s -o /dev/null -w "%{http_code}" https://hub.docker.com/v2/repositories/fischernz/helpme-upload-ms/tags/${VERSION})
            if [ "$response" -eq 200 ]; then
              echo "Docker image with tag $VERSION already exists. Aborting."
              exit 1
            else
              echo "Tag $VERSION does not exist. Proceeding..."
            fi
